version: "3"

volumes:
  metadata_data: {}
  coordinator-overlord_var: {}
  broker_var: {}
  historical_var: {}
  middlemanager_var: {}
  router_var: {}

services:
  druid-postgres:
    image: centos/postgresql-10-centos7:1
    volumes:
      - metadata_data:/var/lib/pgsql/data:Z
    environment:
      - POSTGRESQL_USER=druid_user
      - POSTGRESQL_PASSWORD=FoolishPassword
      - POSTGRESQL_DATABASE=druid
    ports: 
      - "5432:5432"
  druid-zookeeper:
    image: bitnami/zookeeper:3.5.5
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
  druid-coordinator-overlord: 
    image: irfius/s2i-druid:0.15.1
    volumes:
      - coordinator-overlord_var:/app/druid/var
    environment:
      - cluster=coordinator-overlord
      - DRUID_HOST=druid.host=druid-coordinator-overlord
      - ZK_HOST=druid.zk.service.host=druid-zookeeper
      - PG_URL=druid.metadata.storage.connector.connectURI=jdbc:postgresql://druid-postgres:5432/druid
      - PG_USER=druid.metadata.storage.connector.user=druid_user
      - PG_PASSWORD=druid.metadata.storage.connector.password=FoolishPassword
      - S3_STORAGE_BUCKET=druid.storage.bucket=$$DRUID_STORAGE_BUCKET
      - S3_LOGS_BUCKET=druid.indexer.logs.s3Bucket=$$DRUID_LOGS_BUCKET
      - S3_ACCESS_KEY=druid.s3.accessKey=$$S3_ACCESS_KEY
      - S3_SECRET_KEY=druid.s3.secretKey=$$S3_SECRET_KEY
      - AWS_REGION=-Daws.region=$$AWS_REGION
    depends_on:
      - druid-postgres
      - druid-zookeeper
    links:
      - druid-postgres
      - druid-zookeeper
    ports:
      - "8081:8081"
  druid-broker: 
    image: irfius/s2i-druid:0.15.1
    volumes: 
      - broker_var:/app/druid/var
    environment:
      - cluster=broker
      - DRUID_HOST=druid.host=druid-broker
      - ZK_HOST=druid.zk.service.host=druid-zookeeper
      - PG_URL=druid.metadata.storage.connector.connectURI=jdbc:postgresql://druid-postgres:5432/druid
      - PG_USER=druid.metadata.storage.connector.user=druid_user
      - PG_PASSWORD=druid.metadata.storage.connector.password=FoolishPassword
      - S3_STORAGE_BUCKET=druid.storage.bucket=$$DRUID_STORAGE_BUCKET
      - S3_LOGS_BUCKET=druid.indexer.logs.s3Bucket=$$DRUID_LOGS_BUCKET
      - S3_ACCESS_KEY=druid.s3.accessKey=$$S3_ACCESS_KEY
      - S3_SECRET_KEY=druid.s3.secretKey=$$S3_SECRET_KEY
      - AWS_REGION=-Daws.region=$$AWS_REGION
    depends_on:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    links:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    ports:
      - "8082:8082"
  druid-historical: 
    image: irfius/s2i-druid:0.15.1
    volumes: 
      - historical_var:/app/druid/var
    environment:
      - cluster=historical
      - DRUID_HOST=druid.host=druid-historical
      - ZK_HOST=druid.zk.service.host=druid-zookeeper
      - PG_URL=druid.metadata.storage.connector.connectURI=jdbc:postgresql://druid-postgres:5432/druid
      - PG_USER=druid.metadata.storage.connector.user=druid_user
      - PG_PASSWORD=druid.metadata.storage.connector.password=FoolishPassword
      - S3_STORAGE_BUCKET=druid.storage.bucket=$$DRUID_STORAGE_BUCKET
      - S3_LOGS_BUCKET=druid.indexer.logs.s3Bucket=$$DRUID_LOGS_BUCKET
      - S3_ACCESS_KEY=druid.s3.accessKey=$$S3_ACCESS_KEY
      - S3_SECRET_KEY=druid.s3.secretKey=$$S3_SECRET_KEY
      - AWS_REGION=-Daws.region=$$AWS_REGION
    depends_on:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    links:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    ports:
      - "8083:8083"
  druid-middlemanager: 
    image: irfius/s2i-druid:0.15.1
    volumes: 
      - middlemanager_var:/app/druid/var
    environment:
      - cluster=middlemanager
      - JAVA_OPTS=druid.indexer.runner.javaOpts=-server -Xms1g -Xmx1g -XX:MaxDirectMemorySize=1g -Daws.region=$$AWS_REGION -Duser.timezone=UTC -Dfile.encoding=UTF-8 -XX:+ExitOnOutOfMemoryError -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
      - DRUID_HOST=druid.host=druid-middlemanager
      - ZK_HOST=druid.zk.service.host=druid-zookeeper
      - PG_URL=druid.metadata.storage.connector.connectURI=jdbc:postgresql://druid-postgres:5432/druid
      - PG_USER=druid.metadata.storage.connector.user=druid_user
      - PG_PASSWORD=druid.metadata.storage.connector.password=FoolishPassword
      - S3_STORAGE_BUCKET=druid.storage.bucket=$$DRUID_STORAGE_BUCKET
      - S3_LOGS_BUCKET=druid.indexer.logs.s3Bucket=$$DRUID_LOGS_BUCKET
      - S3_ACCESS_KEY=druid.s3.accessKey=$$S3_ACCESS_KEY
      - S3_SECRET_KEY=druid.s3.secretKey=$$S3_SECRET_KEY
      - AWS_REGION=-Daws.region=$$AWS_REGION
    depends_on:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    links:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    ports:
      - "8091:8091"
  druid-router: 
    image: irfius/s2i-druid:0.15.1
    volumes: 
      - router_var:/app/druid/var
    environment:
      - cluster=router
      - DRUID_HOST=druid.host=druid-router
      - ZK_HOST=druid.zk.service.host=druid-zookeeper
      - PG_URL=druid.metadata.storage.connector.connectURI=jdbc:postgresql://druid-postgres:5432/druid
      - PG_USER=druid.metadata.storage.connector.user=druid_user
      - PG_PASSWORD=druid.metadata.storage.connector.password=FoolishPassword
      - S3_STORAGE_BUCKET=druid.storage.bucket=$$DRUID_STORAGE_BUCKET
      - S3_LOGS_BUCKET=druid.indexer.logs.s3Bucket=$$DRUID_LOGS_BUCKET
      - S3_ACCESS_KEY=druid.s3.accessKey=$$S3_ACCESS_KEY
      - S3_SECRET_KEY=druid.s3.secretKey=$$S3_SECRET_KEY
      - AWS_REGION=-Daws.region=$$AWS_REGION
    depends_on:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    links:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    ports:
      - "8888:8888"