version: "3"

volumes:
  metadata_data: {}
  coordinator-overlord_var: {}
  broker_var: {}
  historical_var: {}
  middlemanager_var: {}
  router_var: {}

services:
  druid-postgres:
    image: centos/postgresql-10-centos7:1
    volumes:
      - metadata_data:/var/lib/pgsql/data:Z
    environment:
      - POSTGRESQL_USER=druid_user
      - POSTGRESQL_PASSWORD=FoolishPassword
      - POSTGRESQL_DATABASE=druid
    ports: 
      - "5432:5432"
  druid-zookeeper:
    image: bitnami/zookeeper:3.5.5
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
  druid-coordinator-overlord: 
    image: irfius/s2i-druid:0.15.1
    volumes:
      - coordinator-overlord_var:/app/druid/var
    environment:
      - cluster=coordinator-overlord
    depends_on:
      - druid-postgres
      - druid-zookeeper
    links:
      - druid-postgres
      - druid-zookeeper
    ports:
      - "8081:8081"
  druid-broker: 
    image: irfius/s2i-druid:0.15.1
    volumes: 
      - broker_var:/app/druid/var
    environment:
      - cluster=broker
    depends_on:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    links:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    ports:
      - "8082:8082"
  druid-historical: 
    image: irfius/s2i-druid:0.15.1
    volumes: 
      - historical_var:/app/druid/var
    environment:
      - cluster=historical
    depends_on:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    links:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    ports:
      - "8083:8083"
  druid-middlemanager: 
    image: irfius/s2i-druid:0.15.1
    volumes: 
      - middlemanager_var:/app/druid/var
    environment:
      - cluster=middlemanager
    depends_on:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    links:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    ports:
      - "8091:8091"
  druid-router: 
    image: irfius/s2i-druid:0.15.1
    volumes: 
      - router_var:/app/druid/var
    environment:
      - cluster=router
    depends_on:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    links:
      - druid-postgres
      - druid-zookeeper
      - druid-coordinator-overlord
    ports:
      - "8888:8888"